version: '3.4'

services:
  safecityserver:
    image: mshuvalov/safecity:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8090:8090'     
  
  postgres_image:
    image: postgres:latest
    restart: always
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "safecityuser"
      POSTGRES_PASSWORD: "safecityuser"
      POSTGRES_DB: "safecitydb"